# -*- coding: utf-8 -*-
"""Homelessness_Data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aK_kZrawIAn9qKMGKK76ts009gKRsa32
"""

import pandas as pd

# Connect to Drive
from google.colab import drive
drive.mount('/content/drive')

csv_files = '/content/drive/My Drive/'

df_2007_file = csv_files + 'Homelessness_Data_2007.csv'
df_2008_file = csv_files + 'Homelessness_Data_2008.csv'
df_2009_file = csv_files + 'Homelessness_Data_2009.csv'
df_2010_file = csv_files + 'Homelessness_Data_2010.csv'
df_2011_file = csv_files + 'Homelessness_Data_2011.csv'
# Data reporting better after this date according to Courtney
df_2012_file = csv_files + 'Homelessness_Data_2012.csv'
df_2013_file = csv_files + 'Homelessness_Data_2013.csv'
df_2014_file = csv_files + 'Homelessness_Data_2014.csv'
df_2015_file = csv_files + 'Homelessness_Data_2015.csv'
df_2016_file = csv_files + 'Homelessness_Data_2016.csv'
df_2017_file = csv_files + 'Homelessness_Data_2017.csv'
df_2018_file = csv_files + 'Homelessness_Data_2018.csv'
df_2019_file = csv_files + 'Homelessness_Data_2019.csv'

#df_2012 = pd.read_csv(df_2012_file)
df_2013 = pd.read_csv(df_2013_file)
df_2014 = pd.read_csv(df_2014_file)
df_2015 = pd.read_csv(df_2015_file)
df_2016 = pd.read_csv(df_2016_file)
df_2017 = pd.read_csv(df_2017_file)
df_2018 = pd.read_csv(df_2018_file)
df_2019 = pd.read_csv(df_2019_file)

#df_2012_columns = df_2012.columns
df_2013_columns = df_2013.columns
df_2014_columns = df_2014.columns
df_2015_columns = df_2015.columns
df_2016_columns = df_2016.columns
df_2017_columns = df_2017.columns
df_2018_columns = df_2018.columns
df_2019_columns = df_2019.columns

print(df_2013_columns)
df_2013_participation_rates = ['HMIS Participation Rate (ES,TH,RRH,SH)','ES HMIS Participation Rate','TH HMIS Participation Rate','RRH HMIS Participation Rate','SH HMIS Participation Rate','PSH HMIS Participation Rate']
df_2013_children_columns = ['Total Units for Households with Children (ES,TH,RRH)','Total Beds for Households with Children (ES,TH,RRH)','Total Beds for Households without Children (ES,TH,RRH,SH)','Total Beds for Households with only Children (ES,TH,RRH,SH)',
                    'Total ES Units for Households with Children', 'Total ES Beds for Households with Children', 'Total ES Beds for Households without Children', 'Total ES Beds for Households with only Children',
                    'Total TH Units for Households with Children', 'Total TH Beds for Households with Children', 'Total TH Beds for Households without Children',  'Total TH Beds for Households with only Children',
                    'Total RRH Units for Households with Children', 'Total RRH Beds for Households with Children', 'Total RRH Beds for Households without Children', 'Total RRH Beds for Households with only Children',
                    'Total SH Beds for Households without Children', 'Total SH Beds for Households with only Children', 
                    'Total PSH Units for Households with Children', 'Total PSH Beds for Households with Children', 'Total PSH Beds for Households without Children', 'Total PSH Beds for Households with only Children']

print(df_2014_columns)
df_2014_participation_rates = ['HMIS Participation Rate for Year-Round Beds (ES, TH, SH)','HMIS Participation Rate for Year-Round Beds (ES)','HMIS Participation Rate for Year-Round Beds (TH)',
                               'HMIS Participation Rate for Year-Round Beds (SH)', 'HMIS Participation Rate for Year-Round Beds (RRH & DEM)', 'HMIS Participation Rate for Year-Round Beds (RRH)',
                               'HMIS Participation Rate for Year-Round Beds (DEM)','HMIS Participation Rate for Year-Round Beds (PSH)','HMIS Participation Rate for Year-Round Beds (OPH)']
df_2014_children_columns = ['Total Units for Households with Children (ES, TH, SH)','Total Beds for Households with Children (ES, TH, SH)','Total Beds for Households without Children (ES, TH, SH)','Total Beds for Households with only Children (ES, TH, SH)',
                            'Total Units for Households with Children (ES)', 'Total Beds for Households with Children (ES)', 'Total Beds for Households without Children (ES)', 'Total Beds for Households with only Children (ES)',
                            'Total Units for Households with Children (TH)', 'Total Beds for Households with Children (TH)', 'Total Beds for Households without Children (TH)', 'Total Beds for Households with only Children (TH)',
                            'Total Units for Households with Children (SH)', 'Total Beds for Households with Children (SH)', 'Total Beds for Households without Children (SH)', 'Total Beds for Households with only Children (SH)',
                            'Total Units for Households with Children (RRH & DEM)', 'Total Beds for Households with Children (RRH & DEM)', 'Total Beds for Households without Children (RRH & DEM)', 'Total Beds for Households with only Children (RRH & DEM)',
                            'Total Units for Households with Children (RRH)', 'Total Beds for Households with Children (RRH)', 'Total Beds for Households without Children (RRH)', 'Total Beds for Households with only Children (RRH)',
                            'Total Units for Households with Children (DEM)', 'Total Beds for Households with Children (DEM)', 'Total Beds for Households without Children (DEM)', 'Total Beds for Households with only Children (DEM)',
                            'Total Units for Households with Children (PSH)', 'Total Beds for Households with Children (PSH)', 'Total Beds for Households without Children (PSH)', 'Total Beds for Households with only Children (PSH)',
                            'Total Units for Households with Children (OPH)', 'Total Beds for Households with Children (OPH)', 'Total Beds for Households without Children (OPH)', 'Total Beds for Households with only Children (OPH)']

#df_2012_participation_rates = df_2012[participation_rates]
df_2013_participation_rates = df_2013[df_2013_participation_rates]
df_2014_participation_rates = df_2014[df_2014_participation_rates]

#df_2012_children = df_2012[children_columns]
df_2013_children = df_2013[df_2013_children_columns]
df_2014_children = df_2014[df_2014_children_columns]

df_2015_participation_rates = df_2015[participation_rates]
df_2016_participation_rates = df_2016[participation_rates]
df_2017_participation_rates = df_2017[participation_rates]
df_2018_participation_rates = df_2018[participation_rates]
df_2019_participation_rates = df_2019[participation_rates]

df_2015_children = df_2015[children_columns]
df_2016_children = df_2016[children_columns]
df_2017_children = df_2017[children_columns]
df_2018_children = df_2018[children_columns]
df_2019_children = df_2019[children_columns]